# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c91d0af6edf116866d2c50bbb6d24e4b68c495225bde336be6c0015cdd41ba01b9435e36f3f8a33796a2446de2f68cdeaf3e87109699f2f38d3df012b9f93d81

test:
  secret_key_base: 8b74a51f84f78c45a54451d0e0fdf6a7a4b295bfdc615521055a94602e8e5a8ed62e5ea7203fe9949fe4228029591a6096742959bfa3bf76ff1bc390e301049c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
